/*
 *
 * HomePage constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/HomePage/DEFAULT_ACTION',
  LOAD_TRAVEL_MAP = 'app/HomePage/LOAD_TRAVEL_MAP',
  LOAD_TRAVEL_MAP_SUCCESS = 'app/HomePage/LOAD_TRAVEL_MAP_SUCCESS',
  LOAD_TRAVEL_MAP_ERROR = 'app/HomePage/LOAD_TRAVEL_MAP_ERROR',
  LOAD_FILTER_MAP = 'app/HomePage/LOAD_FILTER_MAP',
  LOAD_FILTER_MAP_SUCCESS = 'app/HomePage/LOAD_FILTER_MAP_SUCCESS',
  LOAD_FILTER_MAP_ERROR = 'app/HomePage/LOAD_FILTER_MAP_ERROR',
  LOAD_PAPER_MAP = 'app/HomePage/LOAD_PAPER_MAP',
  LOAD_PAPER_MAP_SUCCESS = 'app/HomePage/LOAD_PAPER_MAP_SUCCESS',
  LOAD_PAPER_MAP_ERROR = 'app/HomePage/LOAD_PAPER_MAP_ERROR',
  LOAD_POST_TOP = 'app/HomePage/LOAD_POST_TOP',
  LOAD_POST_TOP_SUCCESS = 'app/HomePage/LOAD_POST_TOP_SUCCESS',
  LOAD_POST_TOP_ERROR = 'app/HomePage/LOAD_POST_TOP_ERROR',
}

export default ActionTypes;
